services:
    mirakurun:
        image: ghcr.io/toruta39/mirakurun:latest-arm32v7
        cap_add:
            - SYS_ADMIN
            - SYS_NICE
        ports:
            - "40772:40772"
            - "9229:9229"
        volumes:
            - ./mirakurun/conf:/app-config
            - ./mirakurun/data:/app-data
        environment:
            TZ: "Asia/Tokyo"
        devices:
            - /dev/bus:/dev/bus
            # - /dev/dvb:/dev/dvb
            - /dev/px4video0:/dev/px4video0
            - /dev/px4video1:/dev/px4video1
            - /dev/px4video2:/dev/px4video2
            - /dev/px4video3:/dev/px4video3
        restart: always
        logging:
            driver: json-file
            options:
                max-file: "1"
                max-size: 10m

    # epgstation:
    #     image: ghcr.io/toruta39/epgstation:v2.10.0
    #     # build:
    #     #     context: ./epgstation
    #     #     dockerfile: debian.Dockerfile
    #     volumes:
    #         - ./epgstation/config:/app/config
    #         - ./epgstation/data:/app/data
    #         - ./epgstation/thumbnail:/app/thumbnail
    #         - ./epgstation/logs:/app/logs
    #         - ./recorded:/app/recorded
    #     environment:
    #         TZ: "Asia/Tokyo"
    #     ports:
    #         - "8888:8888"
    #     restart: always
    #     logging:
    #         driver: json-file
    #         options:
    #             max-file: "1"
    #             max-size: 10m
